### ISSUE TITLE
Not all orders anonymized...

### ISSUE THREAD

**Issue by alexjamesbrown** [quafzi/magento-anonymizer#10]
Used this several times, which has previously worked great -
Just tried this again to re-create our test site, but it looks like not all orders were anonymised -
There's no pattern to it, but it looks like about 50% have been, 50% have not been...

Any ideas what causes this?

**Comment by quafzi** [comment]
@alexjamesbrown On Twitter, you said, this issue did not appear in the latest run. Did you find the problem?
