### ISSUE TITLE
Remove set base urls

### ISSUE THREAD

**Issue by razbakov** [quafzi/magento-anonymizer#6]
please remove set base urls or make it configurable

this can be set by magerun for example

and it won't work for multistore shops

**Comment by quafzi** [comment]
@razbakov Yeah, you're right. I stumbled about that some days ago as well.

**Comment by razbakov** [comment]
i removed it in #7

**Comment by quafzi** [comment]
@razbakov Could you please test the current version? You may now specify a new URL for every store/website.

Please note, that config files may now contain specific dev database identifiers as well.

**Comment by razbakov** [comment]
baseurl change is still there:
https://github.com/quafzi/magento-anonymizer/blob/master/anonymizer.sh#L205-207

**Comment by quafzi** [comment]
Sorry, I didn't push that branch :/

**Comment by quafzi** [comment]
@razbakov Did that work for you?

**Comment by razbakov** [comment]
is it merged to master?

**Comment by quafzi** [comment]
@razbakov No, it's in https://github.com/quafzi/magento-anonymizer/pull/8
